package com.charlieczh.cxfjms.wsdl2java.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2021-07-04T14:28:36.361+08:00
 * Generated source version: 3.3.5
 *
 */
@WebServiceClient(name = "OrderService",
                  wsdlLocation = "file:/C:/Users/Fast/Downloads/cxf-jms/src/main/resources/schema/OrderService.xml",
                  targetNamespace = "http://service.wsdl2java.cxfjms.charlieczh.com/")
public class OrderService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.wsdl2java.cxfjms.charlieczh.com/", "OrderService");
    public final static QName OrderServicePort = new QName("http://service.wsdl2java.cxfjms.charlieczh.com/", "OrderServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Fast/Downloads/cxf-jms/src/main/resources/schema/OrderService.xml");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OrderService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Fast/Downloads/cxf-jms/src/main/resources/schema/OrderService.xml");
        }
        WSDL_LOCATION = url;
    }

    public OrderService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrderService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public OrderService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OrderService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OrderService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns OrderService
     */
    @WebEndpoint(name = "OrderServicePort")
    public OrderService getOrderServicePort() {
        return super.getPort(OrderServicePort, OrderService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderService
     */
    @WebEndpoint(name = "OrderServicePort")
    public OrderService getOrderServicePort(WebServiceFeature... features) {
        return super.getPort(OrderServicePort, OrderService.class, features);
    }

}
